<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-16T13:29:30 IST" name="FaceBookV1" finished-at="2021-05-16T13:29:35 IST" duration-ms="4194">
    <groups>
    </groups>
    <test started-at="2021-05-16T13:29:30 IST" name="FaceBookapp" finished-at="2021-05-16T13:29:35 IST" duration-ms="4194">
      <class name="com.FaceBook.Testcases.TC_LoginPage_DDT_001">
        <test-method is-config="true" signature="SetUp(java.lang.String)[pri:0, instance:com.FaceBook.Testcases.TC_LoginPage_DDT_001@550ee7e5]" started-at="2021-05-16T13:29:31 IST" name="SetUp" finished-at="2021-05-16T13:29:35 IST" duration-ms="4094" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="LoginTestDDT(java.lang.String, java.lang.String)[pri:0, instance:com.FaceBook.Testcases.TC_LoginPage_DDT_001@550ee7e5]" started-at="2021-05-16T13:29:35 IST" name="LoginTestDDT" data-provider="LogintestDDT" finished-at="2021-05-16T13:29:35 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.FaceBook.Testcases.TC_LoginPage_DDT_001.LoginTestDDT(java.lang.String,java.lang.String) throws java.lang.Exception requires a @DataProvider named : LogintestDDT]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.FaceBook.Testcases.TC_LoginPage_DDT_001.LoginTestDDT(java.lang.String,java.lang.String) throws java.lang.Exception requires a @DataProvider named : LogintestDDT
at org.testng.internal.Parameters.findDataProvider(Parameters.java:559)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestDDT -->
      </class> <!-- com.FaceBook.Testcases.TC_LoginPage_DDT_001 -->
    </test> <!-- FaceBookapp -->
  </suite> <!-- FaceBookV1 -->
</testng-results>
